---
services:
  myapps_api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: myapps_api
    container_name: myapps_api
    volumes:
      - ./api:/app:z
      - ./api/static:/app/static
    ports:
      - "8001:8000"
    # expose:
    #   - "8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - myapps_postgres_db
    command: /start
    networks:
      - myApps_nw

  myapps_postgres_db:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: myapps_postgres_db
    container_name: myapps_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - myapps_postgres_db_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - myApps_nw

networks:
  myApps_nw:

volumes:
  myapps_postgres_db_data: {}
