---
services:
  myapps_api: &myapps_api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: myapps_api
    container_name: myapps_api
    volumes:
      - ./api:/app:z
      - static_data:/app/static
    expose:
      - "8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - myapps_postgres_db
      - myapps_redis
    command: /start
    networks:
      - myApps_nw

  myapps_postgres_db:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    image: myapps_postgres_db
    container_name: myapps_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - myapps_postgres_db_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - myApps_nw
  myapps_client:
    build:
      context: ./client
      dockerfile: ../docker/local/react/Dockerfile
    image: myapps_client
    container_name: myapps_client
    expose:
      - "5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - myApps_nw

  myapps_redis:
    image: redis:7.2.5-alpine3.20
    command: redis-server --appendonly yes
    container_name: myapps_redis
    volumes:
      - myapps_redis_data:/data
    networks:
      - myApps_nw

  myapps_celery_worker:
    <<: *myapps_api
    image: myapps_celery_worker
    container_name: myapps_celery_worker
    command: /start-celeryworker

  myapps_celery_beat:
    <<: *myapps_api
    image: myapps_celery_beat
    container_name: myapps_celery_beat
    command: /start-celerybeat

  myapps_flower:
    <<: *myapps_api
    image: myapps_flower
    container_name: myapps_flower
    ports:
      - "5555:5555"
    command: /start-flower

  myapps_nginx:
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    image: myapps_nginx
    container_name: myapps_nginx
    ports:
      - "8080:80"
    volumes:
      - ./static:/app/static
      - static_data:/app/static
      - myapps_logs_store:/var/log/nginx
    depends_on:
      - myapps_api
    networks:
      - myApps_nw

networks:
  myApps_nw:

volumes:
  myapps_postgres_db_data: {}
  myapps_logs_store: {}
  static_data: {}
  myapps_redis_data: {}
