---
services:
  myapps_api:
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: myapps_api
    container_name: myapps_api
    restart: always
    volumes:
      - static_volume:/app/static
    # ports:
    #   - "8001:8000"
    expose:
      - "8000"
    env_file:
      - ./.envs/.env.production
    depends_on:
      - myapps_postgres_db
    command: /start
    networks:
      - myApps_nw

  myapps_postgres_db:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: myapps_postgres_db
    container_name: myapps_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - myapps_postgres_db_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.production
    restart: always
    networks:
      - myApps_nw
  myapps_nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    image: myapps_nginx
    container_name: myapps_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - static_volume:/app/static
      - client_volume:/app/dist
      - myapps_logs_store:/var/log/nginx
    depends_on:
      - myapps_api
    networks:
      - myApps_nw

networks:
  myApps_nw:

volumes:
  myapps_postgres_db_data: {}
  myapps_logs_store: {}
  static_volume: {}
  client_volume: {}
