# Generated by Django 5.0.7 on 2024-10-28 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkShift",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=100)),
                ("start_of_shift", models.TimeField()),
                ("end_of_shift", models.TimeField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_shift_profile",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkDay",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "type_of_work_day",
                    models.CharField(
                        choices=[
                            ("Travel", "Travel"),
                            ("Work Day", "Normal Day"),
                            ("Weekend", "Weekend"),
                            ("Times off", "Times Off"),
                            ("Sick Leave", "Sick Leave"),
                            ("Public Holiday", "Public Holiday"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_start", models.DateField(unique=True)),
                ("date_end", models.DateField(blank=True, null=True, unique=True)),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                ("start_of_work", models.TimeField(blank=True, null=True)),
                ("end_of_work", models.TimeField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_day_profile",
                        to="profiles.profile",
                    ),
                ),
                (
                    "work_day_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work_hours.workshift",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_start"],
            },
        ),
    ]
