# Generated by Django 5.0.7 on 2025-08-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_hours", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workday",
            options={"ordering": ["-date"]},
        ),
        migrations.RenameField(
            model_name="workday",
            old_name="date_start",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="workday",
            name="date_end",
        ),
    ]
