# Generated by Django 5.0.7 on 2024-10-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_hours", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshift",
            options={"ordering": ["-created_at"]},
        ),
    ]
