# Generated by Django 5.0.7 on 2024-10-26 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
        ("work_hours", "0002_alter_workshift_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkDay",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "type_of_work_day",
                    models.CharField(
                        choices=[
                            ("Travel", "Travel"),
                            ("Work Day", "Normal Day"),
                            ("Weekend", "Weekend"),
                            ("Times off", "Times Off"),
                            ("Sick Leave", "Sick Leave"),
                            ("Public Holiday", "Public Holiday"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=150, null=True)),
                ("start_of_work", models.TimeField(blank=True, null=True)),
                ("end_of_work", models.TimeField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_day_profile",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_start"],
            },
        ),
    ]
