# Generated by Django 5.0.7 on 2024-10-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_hours", "0003_workday"),
    ]

    operations = [
        migrations.AddField(
            model_name="workday",
            name="work_day_shift",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="work_hours.workshift",
            ),
            preserve_default=False,
        ),
    ]
