# Generated by Django 5.0.7 on 2024-10-26 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_hours", "0004_workday_work_day_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workday",
            name="work_day_shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="work_hours.workshift",
            ),
        ),
    ]
