# Generated by Django 5.0.7 on 2024-10-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_hours", "0005_alter_workday_work_day_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workday",
            name="date_start",
            field=models.DateField(unique=True),
        ),
    ]
