# Generated by Django 5.0.7 on 2024-10-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_hours", "0006_alter_workday_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workday",
            name="date_end",
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
