# Generated by Django 5.0.7 on 2024-10-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymmachine",
            name="machine_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
