# Generated by Django 5.0.7 on 2024-09-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diarydate",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="diarynotes",
            options={"ordering": ["-note_type", "time"]},
        ),
    ]
