# Generated by Django 5.0.7 on 2024-08-11 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Todo List Title"),
                ),
                (
                    "complete_until",
                    models.DateTimeField(verbose_name="Todo Complete Time"),
                ),
                ("expired", models.BooleanField(default=False)),
                (
                    "completed_in_time",
                    models.BooleanField(
                        default=False, verbose_name="Is Completed In Time"
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["completed", "expired", "complete_until"],
            },
        ),
        migrations.CreateModel(
            name="TodoTasks",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Todo Name")),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "todo_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todo",
                        to="todos.todo",
                    ),
                ),
            ],
            options={
                "ordering": ["is_completed"],
            },
        ),
    ]
