# Generated by Django 5.0.7 on 2024-08-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todotasks",
            options={"ordering": ["-is_completed"]},
        ),
    ]
