# Generated by Django 5.0.7 on 2024-10-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todotasks",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Todo Name"),
        ),
    ]
