# Generated by Django 5.0.7 on 2024-08-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_alter_todotasks_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["completed", "expired"]},
        ),
    ]
