# Generated by Django 5.0.7 on 2024-08-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ["completed", "expired", "complete_until"]},
        ),
    ]
