# Generated by Django 5.0.7 on 2024-10-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutritionday",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="nutrition",
            name="total_calories",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="nutritionday",
            name="total_foods_calories",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
