# Generated by Django 5.0.7 on 2024-10-23 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nutrition_tracker", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionday",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutritions_profile",
                to="profiles.profile",
                verbose_name="Nutrition Profile",
            ),
        ),
        migrations.AddField(
            model_name="nutrition",
            name="nutrition_day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_day",
                to="nutrition_tracker.nutritionday",
                verbose_name="Nutrition Day",
            ),
        ),
        migrations.AddField(
            model_name="targetkilograms",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
    ]
