# Generated by Django 5.0.7 on 2024-10-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nutrition_tracker",
            "0002_alter_nutritionday_options_alter_nutrition_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooddata",
            name="food_calories",
            field=models.FloatField(),
        ),
    ]
